# Generated by Django 6.0 on 2025-12-15 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_imageproject_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageproject',
            name='settings',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
