# Generated by Django 6.0 on 2026-01-23 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_imageproject_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageproject',
            name='gen_seed',
            field=models.IntegerField(blank=True, help_text='Random seed for reproducibility', null=True),
        ),
        migrations.AddField(
            model_name='imageproject',
            name='gen_steps',
            field=models.IntegerField(blank=True, help_text='Number of inference steps', null=True),
        ),
        migrations.AddField(
            model_name='imageproject',
            name='gen_style',
            field=models.CharField(blank=True, choices=[('photorealistic', 'Photorealistic'), ('artistic', 'Artistic'), ('anime', 'Anime')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='imageproject',
            name='prompt',
            field=models.TextField(blank=True, help_text='Text prompt for AI generation', null=True),
        ),
        migrations.AddField(
            model_name='imageproject',
            name='source',
            field=models.CharField(choices=[('uploaded', 'Uploaded'), ('generated', 'Generated')], default='uploaded', max_length=20),
        ),
        migrations.AlterField(
            model_name='imageproject',
            name='original_image',
            field=models.ImageField(blank=True, null=True, upload_to='originals/'),
        ),
    ]
