# Generated by Django 4.2.28 on 2026-03-24 04:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0004_imageproject_gen_seed_imageproject_gen_steps_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FactCheckRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_claim', models.TextField(blank=True, null=True)),
                ('claim', models.TextField()),
                ('verdict', models.CharField(max_length=50)),
                ('confidence', models.FloatField()),
                ('explanation', models.TextField()),
                ('evidence', models.JSONField(blank=True, default=list)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
