# Generated by Django 4.2.28 on 2026-03-27 13:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0006_sharedresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntelligenceReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('topic', models.TextField()),
                ('verdict', models.CharField(max_length=50)),
                ('confidence_score', models.FloatField(default=0)),
                ('bias_score', models.FloatField(default=0)),
                ('summary', models.TextField()),
                ('reasoning', models.JSONField(default=list)),
                ('context', models.TextField(blank=True, null=True)),
                ('sources', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('data_mode', models.CharField(default='real', max_length=20)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NarrativeMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('narrative_type', models.CharField(max_length=100)),
                ('sentiment_score', models.FloatField()),
                ('volume_percentage', models.FloatField()),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='narratives', to='api.intelligencereport')),
            ],
        ),
        migrations.CreateModel(
            name='EntityMention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('entity_type', models.CharField(choices=[('person', 'Person'), ('org', 'Organization'), ('loc', 'Location'), ('event', 'Event')], max_length=20)),
                ('frequency', models.IntegerField(default=1)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entities', to='api.intelligencereport')),
            ],
        ),
    ]
