# Generated by Django 4.2.30 on 2026-04-15 07:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0009_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminActivityLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('login', 'Admin Login'), ('login_failed', 'Failed Login Attempt'), ('logout', 'Admin Logout'), ('view_dashboard', 'Viewed Dashboard'), ('view_users', 'Viewed Users List'), ('view_analytics', 'Viewed Analytics'), ('ban_user', 'Banned User'), ('unban_user', 'Unbanned User'), ('promote_user', 'Promoted User to Staff'), ('view_jobs', 'Viewed Jobs'), ('view_activity', 'Viewed Activity Logs'), ('export_data', 'Exported Data'), ('other', 'Other Action')], max_length=50)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('admin_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_actions', to=settings.AUTH_USER_MODEL)),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_actions_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admin Activity Log',
                'verbose_name_plural': 'Admin Activity Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['action', 'timestamp'], name='api_adminac_action_95ec4b_idx'), models.Index(fields=['admin_user', 'timestamp'], name='api_adminac_admin_u_60c93c_idx')],
            },
        ),
    ]
