# Generated by Django 4.2.30 on 2026-04-15 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_adminactivitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageproject',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
