# Generated by Django 4.2.30 on 2026-04-15 14:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_featureblog_delete_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('category', models.CharField(choices=[('Technical Support', 'Technical Support'), ('Enterprise API', 'Enterprise API'), ('Billing & Subscriptions', 'Billing & Subscriptions'), ('Feature Request', 'Feature Request'), ('Other', 'Other')], default='Other', max_length=50)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('unread', 'Unread'), ('read', 'Read'), ('replied', 'Replied')], default='unread', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='FeatureBlog',
        ),
    ]
