"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Load .env explicitly relative to settings.py's parent (the 'backend' folder's parent = django root)
_DJANGO_ROOT = Path(__file__).resolve().parent.parent
load_dotenv(dotenv_path=_DJANGO_ROOT / '.env', override=True)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-fallback-dev-key-change-in-prod')

# Gemini API Key for text-to-image generation
GEMINI_API_KEY = os.environ.get('GEMINI_API_KEY', '')

# Razorpay Subscription Settings
RAZORPAY_KEY_ID = os.environ.get('RAZORPAY_KEY_ID', 'rzp_test_placeholder')
RAZORPAY_KEY_SECRET = os.environ.get('RAZORPAY_KEY_SECRET', 'placeholder_secret')

# Default to False for production
DEBUG = os.environ.get('DEBUG', 'False') == 'True'

import re

# Parse ALLOWED_HOSTS from env (handles both space and comma separated)
env_hosts = os.environ.get('ALLOWED_HOSTS', '*')
ALLOWED_HOSTS = ['*'] # Temporarily allow all for debugging connection issues

# Allow Railway internal networking
if os.environ.get('RAILWAY_STATIC_URL'):
    ALLOWED_HOSTS.append(os.environ.get('RAILWAY_STATIC_URL'))
if os.environ.get('RAILWAY_PUBLIC_DOMAIN'):
    ALLOWED_HOSTS.append(os.environ.get('RAILWAY_PUBLIC_DOMAIN'))


INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'rest_framework_simplejwt',
    'api',
    'subscriptions',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'api.admin_middleware.AdminJWTMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

REST_FRAMEWORK = {
    # Authentication
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    
    # Rate Limiting (Throttling)
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
        'rest_framework.throttling.ScopedRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '200/minute',     # Anonymous users: 200 requests/minute (for rapid suggestions)
        'user': '1000/minute',    # Authenticated users: 1000 requests/minute
        'ai_generation': '5/minute', # Strict limit for AI generation
    },
    
    # Pagination
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    
    # Filtering & Ordering
    'DEFAULT_FILTER_BACKENDS': [
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
}

# Cache Configuration
# Redis is recommended for distributed rate limiting and abuse controls.
REDIS_URL = os.environ.get('REDIS_URL', '').strip()
if REDIS_URL:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.redis.RedisCache',
            'LOCATION': REDIS_URL,
            'TIMEOUT': 300,
        }
    }
else:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'fixpix-local-cache',
        }
    }

from datetime import timedelta
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
}

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database Configuration
# Uses PostgreSQL in production (DATABASE_URL), SQLite in development
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

# Check for DATABASE_URL environment variable (production)
DATABASE_URL = os.environ.get('DATABASE_URL')

if DATABASE_URL:
    # PostgreSQL configuration for production
    # Expected format: postgres://USER:PASSWORD@HOST:PORT/DB_NAME
    import dj_database_url
    DATABASES = {
        'default': dj_database_url.config(
            default=DATABASE_URL,
            conn_max_age=600,
            conn_health_checks=True,
        )
    }
else:
    # SQLite for local development
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Media Files / Cloud Storage Configuration
# Supports: AWS S3, Cloudinary, or local storage (default)

# Detect storage provider from environment
STORAGE_PROVIDER = os.environ.get('STORAGE_PROVIDER', 'local').lower()

if STORAGE_PROVIDER == 's3':
    # AWS S3 Configuration
    INSTALLED_APPS += ['storages']
    
    AWS_ACCESS_KEY_ID = os.environ.get('AWS_ACCESS_KEY_ID')
    AWS_SECRET_ACCESS_KEY = os.environ.get('AWS_SECRET_ACCESS_KEY')

    AWS_STORAGE_BUCKET_NAME = os.environ.get('AWS_STORAGE_BUCKET_NAME')
    AWS_S3_REGION_NAME = os.environ.get('AWS_S3_REGION_NAME', 'us-east-1')
    AWS_S3_CUSTOM_DOMAIN = f'{AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com'
    AWS_S3_OBJECT_PARAMETERS = {'CacheControl': 'max-age=86400'}
    AWS_DEFAULT_ACL = 'public-read'
    
    STORAGES = {
        'default': {'BACKEND': 'storages.backends.s3boto3.S3Boto3Storage'},
        'staticfiles': {'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage'},
    }
    MEDIA_URL = f'https://{AWS_S3_CUSTOM_DOMAIN}/media/'

elif STORAGE_PROVIDER == 'cloudinary':
    # Cloudinary Configuration
    INSTALLED_APPS += ['cloudinary', 'cloudinary_storage']
    
    CLOUDINARY_STORAGE = {
        'CLOUD_NAME': os.environ.get('CLOUDINARY_CLOUD_NAME'),
        'API_KEY': os.environ.get('CLOUDINARY_API_KEY'),
        'API_SECRET': os.environ.get('CLOUDINARY_API_SECRET'),
    }
    
    STORAGES = {
        'default': {'BACKEND': 'cloudinary_storage.storage.MediaCloudinaryStorage'},
        'staticfiles': {'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage'},
    }
    MEDIA_URL = '/media/'

else:
    # Local storage (default for development AND Render free tier)
    MEDIA_URL = '/media/'
    MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
    
    # For production without cloud storage, we need to serve media files
    # through a custom view since Django's static() only works in DEBUG mode

# CORS Configuration
# Standard local development origins + Android emulator IP + Production URLs
default_cors_origins = [
    'http://localhost:5173',
    'http://127.0.0.1:5173',
    'http://localhost:3000',
    'http://127.0.0.1:3000',
    'http://localhost:5174',
    'http://127.0.0.1:5174',
    'http://localhost:8000',
    'http://127.0.0.1:8000',
    'http://localhost',
    'http://127.0.0.1',
    'http://10.0.2.2:8000', # Android Emulator
    # Production URLs
    'https://fixpix-fronted.vercel.app',
    'https://fixpix-backend-production.up.railway.app',
    'https://www.fixpix.in',
    'https://fixpix.in',
]

env_cors = os.environ.get('CORS_ALLOWED_ORIGINS', ' '.join(default_cors_origins))
CORS_ALLOWED_ORIGINS = re.split(r'[\s,]+', env_cors)

# Add production URL if defined in environment
prod_cors = os.environ.get('PRODUCTION_URL')
if prod_cors:
    CORS_ALLOWED_ORIGINS.append(prod_cors)

CORS_ALLOW_ALL_ORIGINS = os.environ.get('CORS_ALLOW_ALL_ORIGINS', 'False') == 'True'

# CSRF Configuration
env_csrf = os.environ.get('CSRF_TRUSTED_ORIGINS', 'https://fixpix-fronted.vercel.app,https://fixpix-backend-production.up.railway.app,https://www.fixpix.in,https://fixpix.in')
CSRF_TRUSTED_ORIGINS = re.split(r'[\s,]+', env_csrf)

# Allow Railway internal networking
# ALLOWED_HOSTS = re.split(r'[\s,]+', env_hosts) # Already handled at top


# Celery Configuration
# In production: set CELERY_BROKER_URL to Redis/RabbitMQ
CELERY_BROKER_URL = os.environ.get('CELERY_BROKER_URL', '')
CELERY_RESULT_BACKEND = os.environ.get('CELERY_RESULT_BACKEND', '')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'UTC'

# Local Development: Run tasks synchronously (no Redis needed)
if DEBUG or not CELERY_BROKER_URL:
    CELERY_TASK_ALWAYS_EAGER = True
# Stability AI Configuration
STABILITY_API_KEYS = [k.strip() for k in os.environ.get('STABILITY_API_KEYS', '').split(',') if k.strip()]

# Photoroom Configuration
PHOTOROOM_API_KEY = os.environ.get('PHOTOROOM_API_KEY', '')
PHOTOROOM_SANDBOX = os.environ.get('PHOTOROOM_SANDBOX', 'False') == 'True'
