# Generated by Django 4.2.28 on 2026-04-09 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='name',
            field=models.CharField(choices=[('free', 'Free'), ('pro', 'Pro'), ('elite', 'Elite'), ('pro_yearly', 'Pro Yearly'), ('elite_yearly', 'Elite Yearly')], max_length=50, unique=True),
        ),
    ]
