# Generated by Django 4.2 on 2026-04-20

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_alter_subscriptionplan_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('FREE', 'Free'), ('PRO', 'Pro'), ('ELITE', 'Elite')], default='FREE', max_length=10)),
                ('daily_usage', models.PositiveIntegerField(default=0)),
                ('last_reset_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('features', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=models.deletion.CASCADE, related_name='user_plan', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
