# Generated by Django 4.2.30 on 2026-04-20 05:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subscriptions', '0003_userplan'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsageEventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(max_length=16)),
                ('feature_used', models.CharField(max_length=100)),
                ('cost', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('response_time_ms', models.PositiveIntegerField(default=0)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('status', models.CharField(default='allowed', max_length=16)),
                ('notes', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'created_at'], name='subscriptio_user_id_82581a_idx'), models.Index(fields=['plan', 'feature_used'], name='subscriptio_plan_af984a_idx'), models.Index(fields=['status'], name='subscriptio_status_0922ea_idx')],
            },
        ),
        migrations.CreateModel(
            name='DailyUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('edits_used', models.PositiveIntegerField(default=0)),
                ('upscale_used', models.PositiveIntegerField(default=0)),
                ('bg_remove_used', models.PositiveIntegerField(default=0)),
                ('last_request_at', models.DateTimeField(blank=True, null=True)),
                ('rapid_request_count', models.PositiveIntegerField(default=0)),
                ('abuse_score', models.PositiveIntegerField(default=0)),
                ('blocked_until', models.DateTimeField(blank=True, null=True)),
                ('is_hard_blocked', models.BooleanField(default=False)),
                ('last_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('last_image_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('same_image_repeat_count', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_usage_rows', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'date'], name='subscriptio_user_id_312584_idx'), models.Index(fields=['date'], name='subscriptio_date_1d5769_idx'), models.Index(fields=['blocked_until'], name='subscriptio_blocked_af6467_idx')],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
